source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
    gem 'jekyll-environment-variables'
    gem 'jekyll-paginate'
    gem "webrick", "~> 1.7"
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
end
